title: jekyll-theme-p3
author: Florian Kromer
email: thinwyk@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  A jekyll theme for pattern mining using GitHub Pages.
baseurl: "/p3"
github_username: fkromer

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
